export const FALLBACK_REAL_STUDENTS = [
    {
        "student_id": "22BTA3CSF10001",
        "name": "Aadarsh Patel",
        "attendance": 81,
        "dsa_score": 68,
        "ml_score": 81,
        "qa_score": 80,
        "projects_score": 89,
        "mock_interview_score": 84,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000001",
        "name": "Aanchal  Khare",
        "attendance": 81,
        "dsa_score": 93,
        "ml_score": 66,
        "qa_score": 76,
        "projects_score": 97,
        "mock_interview_score": 71,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10001",
        "name": "Adarsh  Akulwar",
        "attendance": 80,
        "dsa_score": 75,
        "ml_score": 85,
        "qa_score": 82,
        "projects_score": 83,
        "mock_interview_score": 70,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "23MTA5DSC10002",
        "name": "Aditi  Parashar",
        "attendance": 98,
        "dsa_score": 95,
        "ml_score": 74,
        "qa_score": 68,
        "projects_score": 82,
        "mock_interview_score": 70,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000002",
        "name": "Aditi  Patel",
        "attendance": 96,
        "dsa_score": 74,
        "ml_score": 83,
        "qa_score": 87,
        "projects_score": 80,
        "mock_interview_score": 75,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "24BTA3ARI30002",
        "name": "Aditya Sharma",
        "attendance": 76,
        "dsa_score": 86,
        "ml_score": 93,
        "qa_score": 90,
        "projects_score": 74,
        "mock_interview_score": 81,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25CSF000001",
        "name": "Aishwarya  Tiwari",
        "attendance": 89,
        "dsa_score": 67,
        "ml_score": 71,
        "qa_score": 66,
        "projects_score": 90,
        "mock_interview_score": 77,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3DSC10001",
        "name": "Aneesh  Jain",
        "attendance": 85,
        "dsa_score": 93,
        "ml_score": 70,
        "qa_score": 72,
        "projects_score": 77,
        "mock_interview_score": 85,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10002",
        "name": "Angel  Patne",
        "attendance": 98,
        "dsa_score": 89,
        "ml_score": 77,
        "qa_score": 65,
        "projects_score": 80,
        "mock_interview_score": 74,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000001",
        "name": "Anjali  Singh",
        "attendance": 90,
        "dsa_score": 69,
        "ml_score": 85,
        "qa_score": 78,
        "projects_score": 71,
        "mock_interview_score": 69,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10003",
        "name": "Ankit Yadav",
        "attendance": 75,
        "dsa_score": 90,
        "ml_score": 89,
        "qa_score": 68,
        "projects_score": 97,
        "mock_interview_score": 71,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000002",
        "name": "Anshul  Kushwaha",
        "attendance": 90,
        "dsa_score": 97,
        "ml_score": 94,
        "qa_score": 70,
        "projects_score": 94,
        "mock_interview_score": 67,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25DTA000009",
        "name": "Arya Shiralkar",
        "attendance": 98,
        "dsa_score": 76,
        "ml_score": 92,
        "qa_score": 77,
        "projects_score": 94,
        "mock_interview_score": 79,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25DTA000010",
        "name": "Aryan  Kumar Tiwari",
        "attendance": 83,
        "dsa_score": 93,
        "ml_score": 61,
        "qa_score": 74,
        "projects_score": 72,
        "mock_interview_score": 93,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI11004",
        "name": "Avinash  Singh",
        "attendance": 77,
        "dsa_score": 73,
        "ml_score": 70,
        "qa_score": 75,
        "projects_score": 72,
        "mock_interview_score": 88,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25CSF000003",
        "name": "Ayush  Katare",
        "attendance": 77,
        "dsa_score": 66,
        "ml_score": 60,
        "qa_score": 95,
        "projects_score": 90,
        "mock_interview_score": 94,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25AIM100003",
        "name": "Ayush  Kumar",
        "attendance": 93,
        "dsa_score": 80,
        "ml_score": 71,
        "qa_score": 91,
        "projects_score": 70,
        "mock_interview_score": 92,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25ARI100015",
        "name": "B Raghu Vardhan Naidu",
        "attendance": 96,
        "dsa_score": 83,
        "ml_score": 67,
        "qa_score": 64,
        "projects_score": 86,
        "mock_interview_score": 77,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25ARI100018",
        "name": "Bere Vishwas Varma",
        "attendance": 89,
        "dsa_score": 92,
        "ml_score": 64,
        "qa_score": 89,
        "projects_score": 85,
        "mock_interview_score": 82,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10005",
        "name": "Deepika  Dhakar",
        "attendance": 89,
        "dsa_score": 93,
        "ml_score": 84,
        "qa_score": 77,
        "projects_score": 85,
        "mock_interview_score": 78,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10007",
        "name": "Devdutta  Holkundkar",
        "attendance": 88,
        "dsa_score": 75,
        "ml_score": 69,
        "qa_score": 75,
        "projects_score": 74,
        "mock_interview_score": 69,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3DSC10002",
        "name": "Gargi  Soni",
        "attendance": 90,
        "dsa_score": 82,
        "ml_score": 83,
        "qa_score": 86,
        "projects_score": 99,
        "mock_interview_score": 91,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25ARI100045",
        "name": "Gedela Jagadeesh",
        "attendance": 89,
        "dsa_score": 68,
        "ml_score": 76,
        "qa_score": 84,
        "projects_score": 76,
        "mock_interview_score": 79,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25ARI100046",
        "name": "Gonavath Kousik Naik",
        "attendance": 84,
        "dsa_score": 82,
        "ml_score": 74,
        "qa_score": 87,
        "projects_score": 74,
        "mock_interview_score": 75,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10008",
        "name": "Gyayak  Jain",
        "attendance": 79,
        "dsa_score": 76,
        "ml_score": 86,
        "qa_score": 63,
        "projects_score": 87,
        "mock_interview_score": 73,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25AIM000017",
        "name": "Harsh Gupta",
        "attendance": 87,
        "dsa_score": 85,
        "ml_score": 88,
        "qa_score": 64,
        "projects_score": 77,
        "mock_interview_score": 91,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000003",
        "name": "Harshit  Mourya",
        "attendance": 85,
        "dsa_score": 96,
        "ml_score": 61,
        "qa_score": 93,
        "projects_score": 76,
        "mock_interview_score": 91,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC100004",
        "name": "Harshita  Tiwari",
        "attendance": 86,
        "dsa_score": 85,
        "ml_score": 78,
        "qa_score": 85,
        "projects_score": 72,
        "mock_interview_score": 77,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000005",
        "name": "Kamlesh",
        "attendance": 84,
        "dsa_score": 67,
        "ml_score": 74,
        "qa_score": 94,
        "projects_score": 70,
        "mock_interview_score": 79,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10009",
        "name": "Khushi  Nagpure",
        "attendance": 81,
        "dsa_score": 90,
        "ml_score": 76,
        "qa_score": 69,
        "projects_score": 97,
        "mock_interview_score": 67,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000004",
        "name": "Kirti  Soni",
        "attendance": 77,
        "dsa_score": 68,
        "ml_score": 74,
        "qa_score": 94,
        "projects_score": 91,
        "mock_interview_score": 86,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10010",
        "name": "Kuldeep  Chouhan",
        "attendance": 94,
        "dsa_score": 71,
        "ml_score": 65,
        "qa_score": 66,
        "projects_score": 95,
        "mock_interview_score": 84,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000008",
        "name": "Mayank  Dubey",
        "attendance": 89,
        "dsa_score": 79,
        "ml_score": 76,
        "qa_score": 85,
        "projects_score": 70,
        "mock_interview_score": 66,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000005",
        "name": "Mayank Vishwakarma",
        "attendance": 98,
        "dsa_score": 73,
        "ml_score": 80,
        "qa_score": 96,
        "projects_score": 76,
        "mock_interview_score": 66,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI100006",
        "name": "Mishra Sandeep Azad",
        "attendance": 90,
        "dsa_score": 67,
        "ml_score": 66,
        "qa_score": 95,
        "projects_score": 75,
        "mock_interview_score": 69,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "20MTA5ARI10003",
        "name": "Mitali Saxena",
        "attendance": 94,
        "dsa_score": 83,
        "ml_score": 76,
        "qa_score": 75,
        "projects_score": 88,
        "mock_interview_score": 73,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000009",
        "name": "Mohammed Zubair Khan",
        "attendance": 90,
        "dsa_score": 87,
        "ml_score": 77,
        "qa_score": 73,
        "projects_score": 75,
        "mock_interview_score": 92,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10012",
        "name": "Parikshit  Singh",
        "attendance": 84,
        "dsa_score": 97,
        "ml_score": 67,
        "qa_score": 84,
        "projects_score": 87,
        "mock_interview_score": 89,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10013",
        "name": "Pavitra N Dubey",
        "attendance": 80,
        "dsa_score": 93,
        "ml_score": 64,
        "qa_score": 74,
        "projects_score": 80,
        "mock_interview_score": 91,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000007",
        "name": "Pooja  Kahar",
        "attendance": 85,
        "dsa_score": 74,
        "ml_score": 90,
        "qa_score": 65,
        "projects_score": 75,
        "mock_interview_score": 66,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000008",
        "name": "Poorva  Tiwari",
        "attendance": 89,
        "dsa_score": 66,
        "ml_score": 94,
        "qa_score": 94,
        "projects_score": 70,
        "mock_interview_score": 80,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25AIM000039",
        "name": "Pranay Mourya",
        "attendance": 77,
        "dsa_score": 96,
        "ml_score": 94,
        "qa_score": 68,
        "projects_score": 77,
        "mock_interview_score": 70,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000009",
        "name": "Pratibha Thakur",
        "attendance": 80,
        "dsa_score": 90,
        "ml_score": 75,
        "qa_score": 87,
        "projects_score": 84,
        "mock_interview_score": 93,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000010",
        "name": "Pulkit  Singh",
        "attendance": 97,
        "dsa_score": 67,
        "ml_score": 72,
        "qa_score": 94,
        "projects_score": 82,
        "mock_interview_score": 74,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3CSF10002",
        "name": "Ragni  Kushwaha",
        "attendance": 84,
        "dsa_score": 95,
        "ml_score": 72,
        "qa_score": 72,
        "projects_score": 89,
        "mock_interview_score": 76,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10014",
        "name": "Rajat Tiwari",
        "attendance": 77,
        "dsa_score": 91,
        "ml_score": 69,
        "qa_score": 67,
        "projects_score": 91,
        "mock_interview_score": 76,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000011",
        "name": "Ram Kumar Chouhan",
        "attendance": 93,
        "dsa_score": 84,
        "ml_score": 91,
        "qa_score": 89,
        "projects_score": 89,
        "mock_interview_score": 70,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI100012",
        "name": "Ritesh  Kumar",
        "attendance": 86,
        "dsa_score": 79,
        "ml_score": 74,
        "qa_score": 73,
        "projects_score": 94,
        "mock_interview_score": 88,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10015",
        "name": "Rupesh  Raj",
        "attendance": 76,
        "dsa_score": 87,
        "ml_score": 60,
        "qa_score": 88,
        "projects_score": 73,
        "mock_interview_score": 76,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10016",
        "name": "Sakshi  Kushwaha",
        "attendance": 80,
        "dsa_score": 94,
        "ml_score": 92,
        "qa_score": 94,
        "projects_score": 88,
        "mock_interview_score": 76,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10017",
        "name": "Sarthak Jain",
        "attendance": 81,
        "dsa_score": 98,
        "ml_score": 69,
        "qa_score": 73,
        "projects_score": 78,
        "mock_interview_score": 68,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000014",
        "name": "Shikha",
        "attendance": 86,
        "dsa_score": 97,
        "ml_score": 84,
        "qa_score": 73,
        "projects_score": 92,
        "mock_interview_score": 78,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000015",
        "name": "Shivam  Raghuwanshi",
        "attendance": 86,
        "dsa_score": 93,
        "ml_score": 61,
        "qa_score": 70,
        "projects_score": 82,
        "mock_interview_score": 95,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000016",
        "name": "Shivam Kumar",
        "attendance": 89,
        "dsa_score": 87,
        "ml_score": 75,
        "qa_score": 68,
        "projects_score": 88,
        "mock_interview_score": 72,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000010",
        "name": "Shivani  Jatav",
        "attendance": 80,
        "dsa_score": 77,
        "ml_score": 64,
        "qa_score": 88,
        "projects_score": 94,
        "mock_interview_score": 90,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3CSF10003",
        "name": "Shivani  Kushwaha",
        "attendance": 94,
        "dsa_score": 98,
        "ml_score": 88,
        "qa_score": 83,
        "projects_score": 92,
        "mock_interview_score": 91,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000017",
        "name": "Shivmangal Singh Bhadauriya",
        "attendance": 95,
        "dsa_score": 79,
        "ml_score": 78,
        "qa_score": 91,
        "projects_score": 76,
        "mock_interview_score": 85,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000011",
        "name": "Shubham  Sonkar",
        "attendance": 96,
        "dsa_score": 83,
        "ml_score": 79,
        "qa_score": 64,
        "projects_score": 84,
        "mock_interview_score": 72,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10018",
        "name": "Suhani  Krishna",
        "attendance": 80,
        "dsa_score": 92,
        "ml_score": 63,
        "qa_score": 95,
        "projects_score": 94,
        "mock_interview_score": 66,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25DTA000041",
        "name": "Sumit Dhakad",
        "attendance": 92,
        "dsa_score": 98,
        "ml_score": 67,
        "qa_score": 70,
        "projects_score": 71,
        "mock_interview_score": 91,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24DSC000012",
        "name": "Tanmay  Tripathi",
        "attendance": 94,
        "dsa_score": 78,
        "ml_score": 75,
        "qa_score": 92,
        "projects_score": 77,
        "mock_interview_score": 66,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3CSF10004",
        "name": "Tanvi  Mandloi",
        "attendance": 86,
        "dsa_score": 93,
        "ml_score": 64,
        "qa_score": 82,
        "projects_score": 82,
        "mock_interview_score": 83,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "MTE24ARI000018",
        "name": "Tushar Chawariya",
        "attendance": 80,
        "dsa_score": 77,
        "ml_score": 95,
        "qa_score": 68,
        "projects_score": 89,
        "mock_interview_score": 81,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE24ARI100103",
        "name": "Valakeerthi  Sai Naga Hari Manikanta Babu",
        "attendance": 87,
        "dsa_score": 65,
        "ml_score": 93,
        "qa_score": 63,
        "projects_score": 84,
        "mock_interview_score": 73,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "22BTA3ARI10019",
        "name": "Vedant Dixit",
        "attendance": 93,
        "dsa_score": 70,
        "ml_score": 62,
        "qa_score": 78,
        "projects_score": 92,
        "mock_interview_score": 75,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "BTE25AIM100016",
        "name": "Vinay",
        "attendance": 78,
        "dsa_score": 93,
        "ml_score": 79,
        "qa_score": 74,
        "projects_score": 98,
        "mock_interview_score": 84,
        "batch_id": "Batch 2020"
    },
    {
        "student_id": "23MTA5DSC10001",
        "name": "Aarti",
        "attendance": 82,
        "dsa_score": 69,
        "ml_score": 75,
        "qa_score": 76,
        "projects_score": 89,
        "mock_interview_score": 92,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "20BTA3ARI10012",
        "name": "Aashish Sanodiya",
        "attendance": 93,
        "dsa_score": 68,
        "ml_score": 89,
        "qa_score": 95,
        "projects_score": 82,
        "mock_interview_score": 75,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC10003",
        "name": "Ajay  Yadav",
        "attendance": 90,
        "dsa_score": 80,
        "ml_score": 66,
        "qa_score": 82,
        "projects_score": 73,
        "mock_interview_score": 87,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "MTE24DSC000003",
        "name": "Akhtar Hussain",
        "attendance": 87,
        "dsa_score": 71,
        "ml_score": 90,
        "qa_score": 89,
        "projects_score": 98,
        "mock_interview_score": 84,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10001",
        "name": "Akshat Ranjan Shrivastava",
        "attendance": 76,
        "dsa_score": 87,
        "ml_score": 86,
        "qa_score": 65,
        "projects_score": 88,
        "mock_interview_score": 79,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10002",
        "name": "Aman  Khare",
        "attendance": 75,
        "dsa_score": 72,
        "ml_score": 93,
        "qa_score": 93,
        "projects_score": 95,
        "mock_interview_score": 92,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10003",
        "name": "Amisha  Kohad",
        "attendance": 83,
        "dsa_score": 73,
        "ml_score": 75,
        "qa_score": 68,
        "projects_score": 74,
        "mock_interview_score": 88,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10020",
        "name": "Amit Patel",
        "attendance": 90,
        "dsa_score": 72,
        "ml_score": 88,
        "qa_score": 63,
        "projects_score": 80,
        "mock_interview_score": 89,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10002",
        "name": "Anshul  Rathore",
        "attendance": 98,
        "dsa_score": 93,
        "ml_score": 79,
        "qa_score": 80,
        "projects_score": 93,
        "mock_interview_score": 88,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10003",
        "name": "Anu  Siddharth",
        "attendance": 92,
        "dsa_score": 68,
        "ml_score": 63,
        "qa_score": 70,
        "projects_score": 76,
        "mock_interview_score": 86,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10019",
        "name": "Archi Kirar",
        "attendance": 84,
        "dsa_score": 78,
        "ml_score": 69,
        "qa_score": 94,
        "projects_score": 77,
        "mock_interview_score": 75,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC10004",
        "name": "Ashiya",
        "attendance": 83,
        "dsa_score": 94,
        "ml_score": 89,
        "qa_score": 93,
        "projects_score": 73,
        "mock_interview_score": 90,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10008",
        "name": "Ayush  Lokhande",
        "attendance": 82,
        "dsa_score": 93,
        "ml_score": 84,
        "qa_score": 70,
        "projects_score": 85,
        "mock_interview_score": 81,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10006",
        "name": "Ayush  Sahu",
        "attendance": 77,
        "dsa_score": 84,
        "ml_score": 63,
        "qa_score": 63,
        "projects_score": 87,
        "mock_interview_score": 80,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC11005",
        "name": "Deepak  Kumar",
        "attendance": 87,
        "dsa_score": 80,
        "ml_score": 73,
        "qa_score": 89,
        "projects_score": 74,
        "mock_interview_score": 80,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "20MTA5ARI10004",
        "name": "Deepak Rathore",
        "attendance": 88,
        "dsa_score": 92,
        "ml_score": 75,
        "qa_score": 69,
        "projects_score": 83,
        "mock_interview_score": 73,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10009",
        "name": "Deependra  Patel",
        "attendance": 83,
        "dsa_score": 74,
        "ml_score": 65,
        "qa_score": 85,
        "projects_score": 79,
        "mock_interview_score": 91,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "20MTA5ARI11005",
        "name": "Dushyant Kumar",
        "attendance": 94,
        "dsa_score": 77,
        "ml_score": 83,
        "qa_score": 81,
        "projects_score": 87,
        "mock_interview_score": 66,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10010",
        "name": "Gaurav Kumar Gaur",
        "attendance": 83,
        "dsa_score": 96,
        "ml_score": 84,
        "qa_score": 92,
        "projects_score": 91,
        "mock_interview_score": 82,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10007",
        "name": "Gaurav Singh Kasane",
        "attendance": 91,
        "dsa_score": 65,
        "ml_score": 89,
        "qa_score": 63,
        "projects_score": 81,
        "mock_interview_score": 71,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC11006",
        "name": "Gupta Prince Kumar Jawahar",
        "attendance": 79,
        "dsa_score": 89,
        "ml_score": 80,
        "qa_score": 89,
        "projects_score": 81,
        "mock_interview_score": 73,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10011",
        "name": "Karan  Choudhary",
        "attendance": 79,
        "dsa_score": 65,
        "ml_score": 64,
        "qa_score": 91,
        "projects_score": 78,
        "mock_interview_score": 86,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3CSF10002",
        "name": "Lakshya  Sawner",
        "attendance": 89,
        "dsa_score": 76,
        "ml_score": 69,
        "qa_score": 76,
        "projects_score": 79,
        "mock_interview_score": 72,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "20MTA5CSF10004",
        "name": "Lokendra Argal",
        "attendance": 76,
        "dsa_score": 84,
        "ml_score": 64,
        "qa_score": 65,
        "projects_score": 75,
        "mock_interview_score": 71,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5AIE10004",
        "name": "Mansi  Singh",
        "attendance": 89,
        "dsa_score": 70,
        "ml_score": 92,
        "qa_score": 63,
        "projects_score": 89,
        "mock_interview_score": 83,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10006",
        "name": "Meenar  Uddin",
        "attendance": 86,
        "dsa_score": 92,
        "ml_score": 70,
        "qa_score": 71,
        "projects_score": 85,
        "mock_interview_score": 77,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3CSF10003",
        "name": "Mohit  Yadav",
        "attendance": 93,
        "dsa_score": 94,
        "ml_score": 94,
        "qa_score": 93,
        "projects_score": 88,
        "mock_interview_score": 78,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10012",
        "name": "Neha Kanwar Jhala",
        "attendance": 92,
        "dsa_score": 92,
        "ml_score": 67,
        "qa_score": 85,
        "projects_score": 83,
        "mock_interview_score": 81,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10011",
        "name": "Pallawi  Singh",
        "attendance": 82,
        "dsa_score": 78,
        "ml_score": 70,
        "qa_score": 79,
        "projects_score": 91,
        "mock_interview_score": 73,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC10008",
        "name": "Poonam  Shakya",
        "attendance": 82,
        "dsa_score": 98,
        "ml_score": 64,
        "qa_score": 82,
        "projects_score": 73,
        "mock_interview_score": 71,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3CSF10004",
        "name": "Pranav  Pandey",
        "attendance": 98,
        "dsa_score": 65,
        "ml_score": 92,
        "qa_score": 68,
        "projects_score": 96,
        "mock_interview_score": 73,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3CSF10007",
        "name": "Prateek  Pandya",
        "attendance": 90,
        "dsa_score": 78,
        "ml_score": 78,
        "qa_score": 74,
        "projects_score": 99,
        "mock_interview_score": 88,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10013",
        "name": "Prateeksha  Patel",
        "attendance": 78,
        "dsa_score": 90,
        "ml_score": 93,
        "qa_score": 96,
        "projects_score": 77,
        "mock_interview_score": 81,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "22MTA5AIE10003",
        "name": "Priyanka  Thakur",
        "attendance": 88,
        "dsa_score": 80,
        "ml_score": 77,
        "qa_score": 66,
        "projects_score": 77,
        "mock_interview_score": 86,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10019",
        "name": "Priyanshi Kashyap",
        "attendance": 88,
        "dsa_score": 73,
        "ml_score": 71,
        "qa_score": 69,
        "projects_score": 91,
        "mock_interview_score": 93,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC11009",
        "name": "Priyanshika  Agarwal",
        "attendance": 98,
        "dsa_score": 83,
        "ml_score": 78,
        "qa_score": 81,
        "projects_score": 79,
        "mock_interview_score": 77,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10014",
        "name": "Raj  Choudhary",
        "attendance": 84,
        "dsa_score": 80,
        "ml_score": 80,
        "qa_score": 64,
        "projects_score": 92,
        "mock_interview_score": 92,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10007",
        "name": "Ritesh  Sarathe",
        "attendance": 95,
        "dsa_score": 73,
        "ml_score": 94,
        "qa_score": 66,
        "projects_score": 87,
        "mock_interview_score": 93,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "MTE24ARI000013",
        "name": "Sachin  Verma",
        "attendance": 82,
        "dsa_score": 73,
        "ml_score": 88,
        "qa_score": 68,
        "projects_score": 90,
        "mock_interview_score": 81,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10015",
        "name": "Sakshi Rajput",
        "attendance": 89,
        "dsa_score": 79,
        "ml_score": 61,
        "qa_score": 77,
        "projects_score": 95,
        "mock_interview_score": 69,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10012",
        "name": "Sanjali  Khare",
        "attendance": 78,
        "dsa_score": 92,
        "ml_score": 86,
        "qa_score": 90,
        "projects_score": 94,
        "mock_interview_score": 70,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "20MTA5CSF11001",
        "name": "Sheetakshi\tShukla",
        "attendance": 78,
        "dsa_score": 88,
        "ml_score": 65,
        "qa_score": 84,
        "projects_score": 70,
        "mock_interview_score": 67,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10013",
        "name": "Shubham Mahobia",
        "attendance": 79,
        "dsa_score": 88,
        "ml_score": 68,
        "qa_score": 88,
        "projects_score": 76,
        "mock_interview_score": 80,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10021",
        "name": "Shubhi  Gour",
        "attendance": 83,
        "dsa_score": 74,
        "ml_score": 87,
        "qa_score": 87,
        "projects_score": 98,
        "mock_interview_score": 82,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10016",
        "name": "Siddhant  Shaw",
        "attendance": 90,
        "dsa_score": 95,
        "ml_score": 72,
        "qa_score": 88,
        "projects_score": 84,
        "mock_interview_score": 78,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10014",
        "name": "Taha Siddiqui",
        "attendance": 93,
        "dsa_score": 83,
        "ml_score": 85,
        "qa_score": 79,
        "projects_score": 94,
        "mock_interview_score": 76,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10015",
        "name": "Tanishqa Soni",
        "attendance": 76,
        "dsa_score": 79,
        "ml_score": 62,
        "qa_score": 89,
        "projects_score": 77,
        "mock_interview_score": 93,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10016",
        "name": "Tanya  Shekhawat",
        "attendance": 80,
        "dsa_score": 83,
        "ml_score": 61,
        "qa_score": 69,
        "projects_score": 87,
        "mock_interview_score": 90,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10009",
        "name": "Tejaswini  Dubey",
        "attendance": 78,
        "dsa_score": 88,
        "ml_score": 74,
        "qa_score": 96,
        "projects_score": 92,
        "mock_interview_score": 81,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10017",
        "name": "Uttam Sagar",
        "attendance": 94,
        "dsa_score": 68,
        "ml_score": 63,
        "qa_score": 88,
        "projects_score": 88,
        "mock_interview_score": 77,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3ARI10018",
        "name": "Varun  Gohe",
        "attendance": 85,
        "dsa_score": 96,
        "ml_score": 95,
        "qa_score": 95,
        "projects_score": 92,
        "mock_interview_score": 85,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5DSC10010",
        "name": "Vicky  Prajapati",
        "attendance": 81,
        "dsa_score": 93,
        "ml_score": 68,
        "qa_score": 78,
        "projects_score": 86,
        "mock_interview_score": 72,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10017",
        "name": "Vivek  Mishra",
        "attendance": 80,
        "dsa_score": 91,
        "ml_score": 85,
        "qa_score": 73,
        "projects_score": 77,
        "mock_interview_score": 67,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "23MTA5AIE10007",
        "name": "Yamshi",
        "attendance": 98,
        "dsa_score": 83,
        "ml_score": 90,
        "qa_score": 96,
        "projects_score": 99,
        "mock_interview_score": 77,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3CSF10005",
        "name": "Yash  Patidar",
        "attendance": 85,
        "dsa_score": 83,
        "ml_score": 69,
        "qa_score": 70,
        "projects_score": 87,
        "mock_interview_score": 69,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "21BTA3DSC10018",
        "name": "Yuvraj Singh Solanki",
        "attendance": 90,
        "dsa_score": 78,
        "ml_score": 64,
        "qa_score": 74,
        "projects_score": 76,
        "mock_interview_score": 76,
        "batch_id": "Batch 2021"
    },
    {
        "student_id": "22MTA5CSF10002",
        "name": "Ajay Malviya",
        "attendance": 86,
        "dsa_score": 85,
        "ml_score": 77,
        "qa_score": 93,
        "projects_score": 93,
        "mock_interview_score": 76,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10001",
        "name": "Akshay Bhardwaj",
        "attendance": 75,
        "dsa_score": 81,
        "ml_score": 76,
        "qa_score": 80,
        "projects_score": 86,
        "mock_interview_score": 81,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22BTA3CSF40001",
        "name": "Akshmit  Saxena",
        "attendance": 78,
        "dsa_score": 91,
        "ml_score": 61,
        "qa_score": 64,
        "projects_score": 85,
        "mock_interview_score": 73,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10008",
        "name": "Anuj Choubey",
        "attendance": 92,
        "dsa_score": 84,
        "ml_score": 87,
        "qa_score": 75,
        "projects_score": 72,
        "mock_interview_score": 74,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI11008",
        "name": "Aparna Anand",
        "attendance": 96,
        "dsa_score": 98,
        "ml_score": 65,
        "qa_score": 89,
        "projects_score": 84,
        "mock_interview_score": 76,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10009",
        "name": "Aryan Dhanelia",
        "attendance": 87,
        "dsa_score": 83,
        "ml_score": 90,
        "qa_score": 91,
        "projects_score": 81,
        "mock_interview_score": 78,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI11009",
        "name": "Asar Ahamad",
        "attendance": 89,
        "dsa_score": 66,
        "ml_score": 91,
        "qa_score": 67,
        "projects_score": 83,
        "mock_interview_score": 92,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10002",
        "name": "Avinash Govind Pal",
        "attendance": 85,
        "dsa_score": 72,
        "ml_score": 66,
        "qa_score": 79,
        "projects_score": 77,
        "mock_interview_score": 89,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10003",
        "name": "Bunesh  Athankar",
        "attendance": 94,
        "dsa_score": 91,
        "ml_score": 94,
        "qa_score": 64,
        "projects_score": 88,
        "mock_interview_score": 77,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5AIE10001",
        "name": "Durgesh",
        "attendance": 84,
        "dsa_score": 91,
        "ml_score": 89,
        "qa_score": 96,
        "projects_score": 91,
        "mock_interview_score": 77,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF11001",
        "name": "Faiyaz Ahmad",
        "attendance": 92,
        "dsa_score": 77,
        "ml_score": 61,
        "qa_score": 87,
        "projects_score": 71,
        "mock_interview_score": 73,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10002",
        "name": "Harshita Tiwari",
        "attendance": 83,
        "dsa_score": 89,
        "ml_score": 92,
        "qa_score": 71,
        "projects_score": 97,
        "mock_interview_score": 78,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5BDC10001",
        "name": "Himanshu  Jharaniya",
        "attendance": 84,
        "dsa_score": 88,
        "ml_score": 91,
        "qa_score": 87,
        "projects_score": 96,
        "mock_interview_score": 88,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5CSF10003",
        "name": "Irfan Ahmed Shaikh",
        "attendance": 80,
        "dsa_score": 77,
        "ml_score": 72,
        "qa_score": 66,
        "projects_score": 83,
        "mock_interview_score": 76,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5AIE10002",
        "name": "Jitendra Singh Kustwar",
        "attendance": 92,
        "dsa_score": 66,
        "ml_score": 88,
        "qa_score": 74,
        "projects_score": 78,
        "mock_interview_score": 80,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10003",
        "name": "Koushiki Awasthi",
        "attendance": 79,
        "dsa_score": 83,
        "ml_score": 94,
        "qa_score": 95,
        "projects_score": 83,
        "mock_interview_score": 71,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5CSF10004",
        "name": "Lucky  Pathak",
        "attendance": 80,
        "dsa_score": 82,
        "ml_score": 78,
        "qa_score": 92,
        "projects_score": 97,
        "mock_interview_score": 79,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5BDC10003",
        "name": "Mahesh Kumar Bagwani",
        "attendance": 94,
        "dsa_score": 83,
        "ml_score": 70,
        "qa_score": 95,
        "projects_score": 85,
        "mock_interview_score": 84,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10010",
        "name": "Mayank Vishwakarma",
        "attendance": 95,
        "dsa_score": 83,
        "ml_score": 72,
        "qa_score": 90,
        "projects_score": 83,
        "mock_interview_score": 66,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10004",
        "name": "Mohammad Jishan",
        "attendance": 82,
        "dsa_score": 70,
        "ml_score": 80,
        "qa_score": 90,
        "projects_score": 83,
        "mock_interview_score": 67,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10011",
        "name": "Mohammed Zubair Khan",
        "attendance": 85,
        "dsa_score": 95,
        "ml_score": 89,
        "qa_score": 86,
        "projects_score": 77,
        "mock_interview_score": 68,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10004",
        "name": "Niharika Malik",
        "attendance": 82,
        "dsa_score": 95,
        "ml_score": 78,
        "qa_score": 64,
        "projects_score": 78,
        "mock_interview_score": 88,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5BDC10004",
        "name": "Ripusoodan  Sharma",
        "attendance": 87,
        "dsa_score": 85,
        "ml_score": 74,
        "qa_score": 96,
        "projects_score": 94,
        "mock_interview_score": 95,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10005",
        "name": "Rishabh Jain",
        "attendance": 91,
        "dsa_score": 76,
        "ml_score": 67,
        "qa_score": 94,
        "projects_score": 84,
        "mock_interview_score": 90,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5CSF10007",
        "name": "Shilpa",
        "attendance": 87,
        "dsa_score": 79,
        "ml_score": 84,
        "qa_score": 80,
        "projects_score": 92,
        "mock_interview_score": 84,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10005",
        "name": "Sumit Raghuwanshi",
        "attendance": 97,
        "dsa_score": 67,
        "ml_score": 64,
        "qa_score": 62,
        "projects_score": 83,
        "mock_interview_score": 71,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10006",
        "name": "Suraj Tripathi",
        "attendance": 87,
        "dsa_score": 77,
        "ml_score": 93,
        "qa_score": 76,
        "projects_score": 94,
        "mock_interview_score": 74,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5AIE10004",
        "name": "Swati  Tomar",
        "attendance": 97,
        "dsa_score": 86,
        "ml_score": 88,
        "qa_score": 84,
        "projects_score": 77,
        "mock_interview_score": 95,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3CSF10006",
        "name": "Varun Rajput",
        "attendance": 92,
        "dsa_score": 97,
        "ml_score": 78,
        "qa_score": 73,
        "projects_score": 74,
        "mock_interview_score": 84,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "22MTA5DSC10001",
        "name": "Vishwadeep  Singh",
        "attendance": 80,
        "dsa_score": 91,
        "ml_score": 64,
        "qa_score": 88,
        "projects_score": 89,
        "mock_interview_score": 77,
        "batch_id": "Batch 2022"
    },
    {
        "student_id": "20BTA3ARI10007",
        "name": "Yash Manral",
        "attendance": 80,
        "dsa_score": 79,
        "ml_score": 66,
        "qa_score": 70,
        "projects_score": 91,
        "mock_interview_score": 68,
        "batch_id": "Batch 2022"
    }
];
